### ISSUE TITLE
webase 和编辑器问题反馈

### ISSUE THREAD

**Issue by linbin524** [WeBankFinTech/WeBASE#102]
1、webase 的编辑器列表的合约比较多，有几十个合约，一旦切换到其他功能目录，再切换回来，加载很慢，大概5~9秒左右
2、webase 合约编辑内部是否有自动保存等功能，定时刷新时候，有一定几率出现空白，这个时候如果自己save会出现合约代码消失，保存为空白，解决合约编辑器稳定性问题。

**Comment by teddycode** [comment]
我佛了，今天写了一天的合约突然就被另外一个文件替换了同样的内容，还撤销不了了，也没有备份

**Comment by CodingCattwo** [comment]
感谢反馈！
1. 将在后续版本优化合约加载逻辑，采用按目录加载。
2. 合约IDE在前端失去焦点时，自动保存合约。此功能在webase-web上正常，后续版本将修复webase-front中未自动保存的问题
