### ISSUE TITLE
WeBase合约管理问题以及建议

### ISSUE THREAD

**Issue by teddycode** [WeBankFinTech/WeBASE#104]
一、问题
   1、合约编辑界面按下Ctrl+s保存时，代码会被全选，光标定位消失，很不方便。
   2、已经部署的合约没法删除，也没法更新版本。
   3、编译、部署和调试需要频繁点击右上角，比较费劲。
   4、交易回滚导致部署失败的合约也显示部署成功，地址为0.

二、建议
   1、结合CNS服务提供IDE界面对合约的版本管理。
   2、参考RemixIDE，将IDE界面右上角的操作放在右侧边面板中。

**Comment by karlwanghn** [comment]
确实在合约部署成功后无法进行合约更新，建议增加合约版本功能。

**Comment by CodingCattwo** [comment]
感谢反馈！在后续版本会增加以下功能：
1. 在webase-front前端IDE中支持快捷键进行编译、部署、调用。下一版本添加到webase-web中
2. webase-web中已部署合约不支持修改，如果进行合约调试，可以使用webase-front中的IDE进行调试
3. 部署的合约失败时会判断地址是否为0，此处将修复判断逻辑存在的bug
4. 可以通过console控制台注册CNS进行合约的版本控制
