### ISSUE TITLE
智能合约的函数如果带view修饰，则没办法选择指定的user account 去发送call函数

### ISSUE THREAD

**Issue by lixuandi2018** [WeBankFinTech/WeBASE#124]
智能合约的函数如果带view修饰，则没办法选择指定的user account 去发送读取数据请求。也就是函数中如果使用msg.sender，会有问题。

**Comment by CodingCattwo** [comment]
> 智能合约的函数如果带view修饰，则没办法选择指定的user account 去发送读取数据请求。也就是函数中如果使用msg.sender，会有问题。

不建议在view函数中通过msg.sender进行合约调用者判断~

**Comment by lixuandi2018** [comment]
好的，谢谢
