### ISSUE TITLE
新增节点会造成链重启（其他节点重启），对已有节点造成影响

### ISSUE THREAD

**Issue by yovenchen** [WeBankFinTech/WeBASE#139]
目前新增节点会导致链的重启，即其他节点重启，据我所知和实际操作，只需要新节点配置了所有原节点，就能连上P2P

那么按照现在的情况，会在面临以下两个情况是存在问题：
1.节点正在运作，处理交易，重启会造成影响；
2.节点是属于别的组织的，我新增一个自己机构的节点就把所有重启了，不合理。

希望后续版本能改进，这样更加符合实际场景需求。再次感谢WeBASE的研发小组的努力和群里社群朋友的耐心解答。

祝FISCO BCOS开源社区越办越好！

**Comment by CodingCattwo** [comment]
在v1.4.3后修复为只启动新节点，其余节点默认不重启，并添加了节点重启按钮，方便快速重启节点

**Comment by yovenchen** [comment]
v1.4.3后修复了上述问题
