### ISSUE TITLE
一键部署Webase平台，登录页面的验证码加载不出来

### ISSUE THREAD

**Issue by qzh-hub** [WeBankFinTech/WeBASE#173]
一键部署Webase平台，部署完成后各进程均已启动，但是登陆页面的验证码加载不出来

**Comment by qzh-hub** [comment]
检查了日志，发现是数据库连接出了问题，经过排查，因为我使用的是mysql8，jdbc连接时需要显式指定是否使用SSL

解决方案：修改 /webase-node-mgr/conf/application.yml 和 /webase-sign/conf/application.yml 文件里的url（我添加了 &useSSL=false字段）

**Comment by linkatom** [comment]
我和你问题一样，但是按照你的方法尝试，暂时还没解决问题

**Comment by linkatom** [comment]
我的报错也是在数据库Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'webasenodemanager.tb_app_info' doesn't exist等等一系列缺失
