### ISSUE TITLE
莫名其妙的mgr start fail，完全没有错误信息。

### ISSUE THREAD

**Issue by sheldonzhao** [WeBankFinTech/WeBASE#22]
如图，帮忙看看呗

![Screen Shot 2019-07-08 at 8 53 01 PM](https://user-images.githubusercontent.com/3325919/60811787-90686980-a1c2-11e9-8c31-eea691e30010.png)

**Comment by Sayou1989** [comment]
机器性能问题，会导致服务端口一定时间没起来，脚本就会杀掉进程，新版本已优化（或者可以看一下脚本，修改一下等待时间，出现问题的版本默认20s）
