### ISSUE TITLE
快速搭建WeBASE-front遇到的问题

### ISSUE THREAD

**Issue by darwindu** [WeBankFinTech/WeBASE#36]
按照文档执行，这里没有配置节点ip和端口；然后执行start.sh，执行后，脚本提示success；但是看日志，实际上启动并没有成功；因为我没有文档没有提示我配置节点ip和端口。
这里存在2个问题：
1. 希望文档能够友好的提示我操作的步骤，避免踩坑；例如，以上需要提示我配置ip和端口
2. start.sh脚本启动有问题，front没有启动成功，但是提示成功了，应该是脚本检测的时候有点问题，希望能够跟进一下，给用户更好的体验；

**Comment by Sayou1989** [comment]
好的。
1. 下一版本增加配置说明
2. 新版本已优化脚本

**Comment by mingzhenliu** [comment]
bash start.sh && tail -f log/We.xxx.log
