### ISSUE TITLE
执行到初始化数据库的时候出现以下错误

### ISSUE THREAD

**Issue by cupid5trick** [WeBankFinTech/WeBASE#39]
运行deploy.py部署到初始化数据阶段报错：
![webase部署问题1](https://user-images.githubusercontent.com/50273795/66212844-36a80a80-e6f1-11e9-903d-db6be69a7a8b.png)

大约是说webase.sh 127.0.0.1 3306 命令出错了，然后bash 运行继续报错：找不到webase-sql.list：
![webase部署问题2](https://user-images.githubusercontent.com/50273795/66212867-41fb3600-e6f1-11e9-8edb-07211568ce0a.png)

但是script路径下确实存在这样一个文件，我想知道这是什么问题，该如何解决？

**Comment by Sayou1989** [comment]
1. 新版本已修改为使用bash命令
2. 单独执行需进入script执行
