### ISSUE TITLE
webase 测试环境 合约模块无法打开显示异常

### ISSUE THREAD

**Issue by linbin524** [WeBankFinTech/WeBASE#57]
日志 显示 ### SQL: select * from tb_contract where group_id = ? and contract_bin like CONCAT(?,'%')
### Cause: com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (2,554 > 2,048). You can change this value on the server by setting the 'max_allowed_packet' variable.
; Packet for query is too large (2,554 > 2,048). You can change this value on the server by setting the 'max_allowed_packet' variable.; nested exception is com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (2,554 > 2,048). You can change this value on the server by setting the 'max_allowed_packet' variable.

查找到的错误是：mysql 自动 将 max_allowed_packet 变成2048，把它改为 20M，短暂期间可以使用，但后续有出现变成2048，导致合约模块无法使用，需要排查一下

**Comment by CodingCattwo** [comment]
可以确认一下是否以下原因之一：  
- .cnf的设置不当：mysqld里面控制的是服务端，mysql里面控制的是客户端，如果只设置一处，则当有客户端连接的时候，该值会被重置
- 内存不足：当mysql执行大批次查询语句大时候，因为服务器内存不足，引起预警，mysql会重置这个值，已保证数据库的稳定。
- 黑客攻击
