### ISSUE TITLE
新增链上通知事件接口参数问题

### ISSUE THREAD

**Issue by zoey224** [WeBankFinTech/WeBASE#63]
订阅合约event事件通知接口 http://localhost:5002/WeBASE-Front/event/contractEvent 中，topicList中包含两个及以上事件名时，rabbitMQ就接收不到消息了，请问接口参数示例是否正确？

![image](https://user-images.githubusercontent.com/25894623/77412217-8b068a00-6df8-11ea-9975-1565519f9360.png)

**Comment by mingzhenliu** [comment]
1.3.1修复此bug
