### ISSUE TITLE
怎么升级0.5版本合约编译jar包

### ISSUE THREAD

**Issue by yangjianyao** [WeBankFinTech/WeBASE#64]
我通过一键部署的webase，由于自己的合约是在需要0.5以上的版本。但是这个默认版本是0.42.请问怎么升级？
我看fisco文档提供了升级console合约编译的版本
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/console.html#id11

**Comment by CodingCattwo** [comment]
与console替换方法类似，需要在webase-front的build.gradle中exclude原有的`ethereum`的solcJ包，并通过file文件形式引入。
如果是使用webase的页面进行合约编译，暂时还未支持前端的solc.js版本的替换。在后续版本将会支持该功能特性

另外，最新版webase支持直接在build.gradle中修改solcJ的**版本号**即可使用0.4或0.5的socJ包
