### ISSUE TITLE
在JDK14环境下WeBASE-Front tomcat指定端口无法打开

### ISSUE THREAD

**Issue by N1028YuKi** [WeBankFinTech/WeBASE#70]
更换为8,13都可以正常运行

**Comment by N1028YuKi** [comment]
尝试启动其它Springboot项目，Tomcat可以在jdk14下打开端口正常启动

**Comment by yanyanho** [comment]
> 尝试启动其它Springboot项目，Tomcat可以在jdk14下打开端口正常启动
您好，请问报什么错？有日志信息吗？ 欢迎加入我们fisco 微信群联系我们。

**Comment by CodingCattwo** [comment]
更新web3sdk为2.6.2版本，或将jdk对secp k1曲线的支持打开（部分jdk版本默认禁用），或切换jdk为jdk8
