### ISSUE TITLE
WeBase接口文档中trans/handle接口

### ISSUE THREAD

**Issue by ChenXB1n** [WeBankFinTech/WeBASE#77]
接口文档对于参数contractAbi说明有：“如果没有传入此字段，则从db或cns获取合约abi”，使用WeBase提供的HelloWorld Demo时，项目中的application.yml文件没有这个参数contractAbi，运行程序发交易时不能自动获取合约abi，提示422 null报错，手动添加contractAbi后Demo正常使用，不报错

**Comment by CodingCattwo** [comment]
感谢Pull Request
