### ISSUE TITLE
WeBASE对2.5.x版及以上的支持

### ISSUE THREAD

**Issue by hxiaodon** [WeBankFinTech/WeBASE#86]
从[文档](https://webasedoc.readthedocs.io/zh_CN/latest/docs/WeBASE-Install/developer.html)里看到WeBASE目前有如下限制

_注：目前WeBASE支持FISCO BCOS v2.4.x版本，暂未支持FISCO BCOS 2.5.x_

想问下，最新的2.5.x和2.6.x新添加的功能以及修复的bug是否影响了WeBASE的后向兼容性

谢谢~

**Comment by yuanmomo** [comment]
后续适配时，会考虑向后兼容性的问题和兼容升级的问题。

谢谢反馈～
