### ISSUE TITLE
希望webase 接口提供 数据返回解析功能

### ISSUE THREAD

**Issue by linbin524** [WeBankFinTech/WeBASE#99]
目前webase front 等都提供了接口化请求访问，可以实现在内网情况下的业务接口对接上链，但是还差一些功能，当处理的合约方法是有返回值的，希望在接口中就可以解析判断，不然又要依赖sdk 的解析功能就不方便的。

用了webase的接口功能，就是想剔除sdk，如果sdk用、webase又使用那我们就别成很累赘，一定程度上功能重复太多，如果webase可以支持，以后就可以不用sdk了。

**Comment by CodingCattwo** [comment]
感谢反馈，将在v1.4.2中支持此功能
